config/routes.rb
Rails.application.routes.draw do
  root to: "recipes#index"

  resources :recipes, only: [:index, :show] do
    resources :comments, only: [:create, :index]
    resources :ratings, only: [:create]

    post '/favorite', to: 'favorites#create'
    delete '/unfavorite', to: 'favorites#destroy'

    member do
      post :send_email
    end

    collection do
      post "sync"
    end
  end

  resources :categories, only: [:index, :show]

  resources :users, only: [:create]
  resources :favorites, only: [:index]
  resources :invitations, only: [:new, :create]

  get '/forgot_password', to: 'forgot_passwords#new'
  get '/invalid_token', to: 'pages#invalid_token'
  get '/expired_token', to: 'pages#expired_token'
  resources :forgot_passwords, only: [:create]
  resources :reset_passwords, only: [:show, :create], param: :token

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :require_user, only: [:create, :index, :destroy]

  def index
    @recipes = current_user.favorite_recipes.order(:name)
  end

  def create
    recipe = Recipe.find(params[:recipe_id])
    UserRecipe.new(recipe_id: params[:recipe_id], user_id: current_user.id).save

    render partial: 'favorites/unfavorite_link', locals: { recipe: recipe }
  end

  def destroy
    recipe = Recipe.find_by(id: params[:recipe_id])
    favorite = UserRecipe.find_by(recipe_id: params[:recipe_id], user_id: current_user.id)

    favorite.destroy if favorite

    render partial: 'favorites/favorite_link', locals: { recipe: recipe }
  end
end

app/views/favorites/_favorite_link.html.erb
<%= link_to "", recipe_favorite_path(recipe.id), class: "heart-outline", remote: true, method: 'post', data: { type: "html", action: "ajax:success->favorite#replaceLink" } %>

app/views/favorites/_favorite_links.html.erb
<div data-controller="favorite">
  <% if current_user.favorited? recipe %>
    <%= render 'favorites/unfavorite_link', recipe: recipe %>
  <% else %>
    <%= render 'favorites/favorite_link', recipe: recipe %>
  <% end %>
</div>

app/views/favorites/_unfavorite_link.html.erb
<%= link_to "", recipe_unfavorite_path(recipe.id), method: 'delete', class: "heart-solid", remote: true, data: { type: "html", action: "ajax:success->favorite#replaceLink" } %>

app/views/favorites/index.html.erb
<% content_for :header do %>
  <ul class="nav">
    <li class="nav-item">
      <%= link_to recipes_path, class: "link-icon header-button btn btn-sm" do %>
        <%= octicon "arrow-left" %>
        <p>Back</p>
      <% end %>
    </li>
  </ul>
<% end %>

<div class="recipes-list">
  <h5 class="mb-4 ml-2 mt-2"><span class="heart-solid"></span>Your Favorites</h5>
  <ul class="list-group">
    <%= render @recipes %>
  </ul>
</div>