config/routes.rb
Rails.application.routes.draw do
  root to: "recipes#index"

  resources :recipes, only: [:index, :show] do
    resources :comments, only: [:create, :index]
    resources :ratings, only: [:create]

    post '/favorite', to: 'favorites#create'
    delete '/unfavorite', to: 'favorites#destroy'

    member do
      post :send_email
    end

    collection do
      post "sync"
    end
  end

  resources :categories, only: [:index, :show]

  resources :users, only: [:create]
  resources :favorites, only: [:index]
  resources :invitations, only: [:new, :create]

  get '/forgot_password', to: 'forgot_passwords#new'
  get '/invalid_token', to: 'pages#invalid_token'
  get '/expired_token', to: 'pages#expired_token'
  resources :forgot_passwords, only: [:create]
  resources :reset_passwords, only: [:show, :create], param: :token

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  extend FriendlyId

  friendly_id :name, use: :slugged
  before_save :default_values

  validates :name, presence: true
  validates :ingredients, presence: true
  validates :uid, presence: true
  validates :token, presence: true

  has_many :comments
  has_many :recipe_categories, primary_key: :uid, foreign_key: :recipe_uid
  has_many :categories, through: :recipe_categories
  has_many :ratings

  has_many :user_recipes
  has_many :favorited_by, through: :user_recipes, source: :user

  def should_generate_new_friendly_id?
    name_changed? || super
  end

  def update_average_rating
    return if ratings.blank?
    rounded_average = (ratings.average(:rating) * 2).round / 2.0
    update(average_rating: rounded_average)
  end

  def average_rating_class
    average_rating.split('.').join('') if average_rating
  end

  def self.uids
    all.map(&:uid)
  end

  def self.delete_not_in(uids)
    all.reject { |recipe| uids.include?(recipe.uid) }.each(&:delete)
  end

  private

  def default_values
    self.photo_url = 'placeholder.jpg' if self.photo_url.blank?
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :require_admin, only: [:sync]

  def index
    @recipes = if params[:sort_by] == "created"
                 Recipe.all.order(created: :desc)
               elsif params[:sort_by] == "rating"
                 Recipe.order('average_rating DESC NULLS LAST')
               else
                 Recipe.all.order(:name)
               end
  end

  def show
    @recipe = Recipe.friendly.find(params[:id])
    @categories = @recipe.categories.map(&:name).join(', ')
    @comment = Comment.new
  end

  def sync
    sync = PaprikaSync.new.call

    if sync.successful?
      flash[:success] = "Recipes successfully synced."
    else
      flash[:danger] = sync.error_message
    end

    redirect_to recipes_path
  end

  def send_email
    recipe = Recipe.find(params[:id])
    email = params[:email]
    AppMailer.send_recipe(recipe, email).deliver_now

    respond_to do |format|
      format.html { redirect_to recipe_path(recipe) }
      format.js
    end
  end
end

app/views/recipes/_recipe.html.erb
<li data-target="search.name" data-name="<%= recipe.name %> "class="recipe-list-item py-1 pl-2">
  <%= link_to recipe_path(recipe) do %>
    <div class="d-flex">
      <div>
        <%= render 'shared/recipe_img', recipe: recipe %>
      </div>
      <div class="recipe-list-item-info ml-1 mt-1">
        <h5 class="mb-0"><%= recipe.name %></h5>
        <%= render 'ratings/average_rating', rating_class: recipe.average_rating_class, id: nil %>
      </div>
    </div>
  <% end %>
</li>

app/views/recipes/index.erb
<h1>All Recipes</h1>

<ul>
  <% @recipes.each do |recipe| %>
    <li>
      <%= link_to recipe.name, recipe_path(recipe.id) %>
    </li>
  <% end %>
</ul>

app/views/recipes/index.html.erb
<% content_for :header do %>
  <ul class="nav">
    <li class="nav-item">
      <div class="input-group input-group-sm recipe-search">
        <%= octicon "search" %>
        <input data-target="search.query" data-action="input->search#search" type="text" placeholder="Search by Name" id="search-bar" class="form-control">
      </div>
    </li>
    <li class="recipe-sort nav-item">
      <div class="dropdown">
        <button class="btn btn-sm dropdown-toggle header-button" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= octicon "list-unordered" %>
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <h6 class="dropdown-header">Sort By</h6>
          <%= link_to "Name", recipes_path, class: "dropdown-item" %>
          <%= link_to "Most Recent", recipes_path(sort_by: "created"), class: "dropdown-item" %>
          <%= link_to "Highest Rated", recipes_path(sort_by: "rating"), class: "dropdown-item" %>
        </div>
      </div>
    </li>
  </ul>
<% end %>

<div class="recipes-list">
  <ul class="list-group">
    <%= render @recipes %>
  </ul>
</div>

app/views/recipes/send_email.js.erb
$('#email-close-button').click()

app/views/recipes/show.html.erb
<% content_for :header do %>
  <ul class="nav">
    <li class="nav-item">
      <%= link_to previous_path, class: "header-button btn btn-sm" do %>
        <%= octicon "arrow-left" %>
        <p>Back</p>
      <% end %>
    </li>
   <li class="nav-item">
     <%= render 'shared/email_recipe' %>
    </li>
  </ul>
<% end %>

<div class="container-fluid">
  <div class="row">
    <div class="recipe-heading container-fluid">
      <div class="row  p-2">
        <div class="p-0">
          <%= render 'shared/recipe_img', recipe: @recipe %>
        </div>
        <div class="col mt-1">
          <h4 class="mb-0"><%= @recipe.name %></h4>
          <%= render 'ratings/average_rating', rating_class: @recipe.average_rating_class %>
          <p class="small-font"><em><%= @categories %></em></p>
          <% if @recipe.source %>
            <p class="small-font"><em>From</em>
              <%= link_to @recipe.source, "http://#{@recipe.source}" %>
            </p>
          <% end %>
            <%= render 'favorites/favorite_links', recipe: @recipe if logged_in? %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-5 ingredients pt-3">
      <h5>Ingredients</h5>
      <%= format_ingredients @recipe.ingredients %>
    </div>
    <div class="col-lg-7 directions pt-3">
      <h5>Directions</h5>
      <%= simple_format @recipe.directions %>
    </div>
  </div>

  <% if logged_in? %>
    <div data-controller="ratings" data-ratings-average-rating="<%= @recipe.average_rating %>" data-ratings-user-rating="<%= current_user.rating_for(@recipe) %>">
      <%= render 'ratings/rating_form', recipe: @recipe, rating: current_user.rating_for(@recipe) %>
    </div>
  <% end %>

  <div class="row" data-controller="comments">
    <div class="col pt-3 pb-5">
      <h5 class="pb-4">Comments (<%= @recipe.comments.count %>)
        <% if logged_in? %>
          <%= link_to "►", recipe_comments_path(@recipe.id), class: "comment-arrow", remote: true, data: { type: "html", target: "comments.arrow", action: "ajax:before->comments#handleLink ajax:success->comments#render" } %>
        <% end %>
      </h5>
      <% if logged_in? %>
        <div class="comments" data-target="comments.el"></div>
        <%= render 'comments/new', recipe: @recipe, comment: @comment %>
      <% else %>
        <p>Please <%= link_to "login", login_path %> to view comments</p>
      <% end %>
    </div>
  </div>
</div>