config/routes.rb
Rails.application.routes.draw do
  root to: "recipes#index"

  resources :recipes, only: [:index, :show] do
    resources :comments, only: [:create, :index]
    resources :ratings, only: [:create]

    post '/favorite', to: 'favorites#create'
    delete '/unfavorite', to: 'favorites#destroy'

    member do
      post :send_email
    end

    collection do
      post "sync"
    end
  end

  resources :categories, only: [:index, :show]

  resources :users, only: [:create]
  resources :favorites, only: [:index]
  resources :invitations, only: [:new, :create]

  get '/forgot_password', to: 'forgot_passwords#new'
  get '/invalid_token', to: 'pages#invalid_token'
  get '/expired_token', to: 'pages#expired_token'
  resources :forgot_passwords, only: [:create]
  resources :reset_passwords, only: [:show, :create], param: :token

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
end

app/views/shared/_email_recipe.html.erb
<button type="button" class="btn btn-sm link-icon header-button" data-toggle="modal" data-target="#emailRecipeModal">
  <%= octicon "mail" %>
</button>
<div class="modal fade" id="emailRecipeModal" tabindex="-1" role="dialog" aria-labelledby="emailRecipeModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="emailRecipeModalLabel">Email this Recipe</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
         <%= form_tag send_email_recipe_path(@recipe.id), remote: true do  %>
          <div class="form-group">
            <%= label_tag :email %>
            <%= email_field_tag :email, nil, class: "form-control", required: true %>
          </div>
          <div class="form-group">
            <button type="button" class="btn btn-secondary" id="email-close-button" data-dismiss="modal">Close</button>
            <%= submit_tag 'Send', class: "btn btn-secondary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger">
      <h5>Please fix the following errors:</h5>
      <ul>
        <% obj.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_header.html.erb
<div class="header">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-10 p-0">
        <%= yield :header %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_menu.html.erb
<div class="menu-links">
  <%= link_to recipes_path do %>
    <%= octicon "note" %>
    <p>Recipes <span class="badge"><%= Recipe.count %></span></p>
  <% end %>
  <%= link_to categories_path do %>
    <%= octicon "tag" %>
    <p>Categories <span class="badge"><%= Category.count %></span></p>
  <% end %>

  <% if logged_in? %>
    <%= link_to favorites_path do %>
      <%= octicon "heart" %>
      <p>Favorites <span class="badge"></span></p>
    <% end %>
    <%= link_to new_invitation_path do %>
      <%= octicon "organization" %>
      <p>Invite a Friend</p>
    <% end %>
    <%= link_to logout_path, method: "post" do %>
      <%= octicon "sign-out" %>
      <p>Logout</p>
    <% end %>
  <% else %>
    <%= link_to login_path do %>
      <%= octicon "sign-in" %>
      <p>Login</p>
    <% end %>
  <% end %>
  <% if logged_in? && current_user.admin? %>
    <%= link_to sync_recipes_path, method: "post" do %>
      <%= octicon "sync" %>
      <p>Sync</p>
    <% end %>
  <% end %>
</div>

app/views/shared/_messages.html.erb
<% if flash.keys.any? %>
  <% flash.keys.each do |key| %>
    <div class="alert alert-<%=key %> alert-dismissable fade show" role="alert">
      <%= flash[key] %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
<% end %>

app/views/shared/_recipe_img.html.erb
<%= image_tag recipe.photo_url, class: "recipe-img", onerror: "this.onerror=null;this.src='https://s3-us-west-2.amazonaws.com/renz-recipes/placeholder.jpg'" %>