config/routes.rb
Rails.application.routes.draw do
  root to: "recipes#index"

  resources :recipes, only: [:index, :show] do
    resources :comments, only: [:create, :index]
    resources :ratings, only: [:create]

    post '/favorite', to: 'favorites#create'
    delete '/unfavorite', to: 'favorites#destroy'

    member do
      post :send_email
    end

    collection do
      post "sync"
    end
  end

  resources :categories, only: [:index, :show]

  resources :users, only: [:create]
  resources :favorites, only: [:index]
  resources :invitations, only: [:new, :create]

  get '/forgot_password', to: 'forgot_passwords#new'
  get '/invalid_token', to: 'pages#invalid_token'
  get '/expired_token', to: 'pages#expired_token'
  resources :forgot_passwords, only: [:create]
  resources :reset_passwords, only: [:show, :create], param: :token

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
end

app/models/category.rb
class Category < ActiveRecord::Base
  extend FriendlyId

  friendly_id :name, use: :slugged

  has_many :recipe_categories, primary_key: :uid, foreign_key: :category_uid
  has_many :recipes, through: :recipe_categories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all.order(:name)
  end

  def show
    @category = Category.friendly.find(params[:id])
  end
end

app/views/categories/index.html.erb
<% content_for :header do %>
  <ul class="nav">
    <li class="nav-item">
      <%= link_to recipes_path, class: "link-icon header-button btn btn-sm" do %>
        <%= octicon "arrow-left" %>
        <p>Back</p>
      <% end %>
    </li>
  </ul>
<% end %>

<div class="pt-2">
  <ul>
    <% @categories.each do |category| %>
      <li>
        <%= link_to category_path(category) do %>
          <h5><%= category.name %></h5>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/categories/show.html.erb
<% content_for :header do %>
  <ul class="nav">
    <li class="nav-item">
      <%= link_to categories_path, class: "link-icon header-button btn btn-sm" do %>
        <%= octicon "arrow-left" %>
        <p>Back</p>
      <% end %>
    </li>
  </ul>
<% end %>

<div class="recipes-list">
  <h5 class="mb-4 ml-2 mt-2"><%= @category.name %></h5>
  <ul class="list-group">
    <%= render @category.recipes %>
  </ul>
</div>